# Generated by Django 4.2.6 on 2023-11-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecast_1h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forecast_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
