# Generated by Django 4.2.5 on 2023-11-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Btc', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forecast_1h', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('forecast_24h', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('official_site', models.URLField(default='')),
                ('whitepaper', models.URLField(default='')),
                ('github', models.URLField(default='')),
                ('reddit', models.URLField(default='')),
                ('news', models.TextField(default='')),
                ('about', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
    ]
