# Generated by Django 4.2.5 on 2023-11-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_cryptocurr_delete_cryptocurrency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cryptocurr',
            new_name='Cryptocurrency',
        ),
    ]
