# Generated by Django 4.2.5 on 2023-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_trending_cryptocurrencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
