# Generated by Django 4.2.5 on 2023-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_remove_cryptocurrency_total_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
