# Generated by Django 4.2.5 on 2023-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_usercryptoholdings_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(default='Btc', max_length=10),
        ),
    ]
